# Site settings
name: 个人笔记
email: jv0id@foxmail.com
author: jv0id
url: http://8void.cn/
resume_site: ''
github: http://8void.cn/
baseurl: ''
description: 平时记录
meta_description: 只好色，不花心。说脏话，不骂人。耍流氓，懂礼貌。
motto: 个人笔记
banner: 学而不思则罔 思而不学则殆
revolvermaps: ''

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
# 一页有几篇文章
paginate: 10
paginate_path: 'page:num'

# 设置时区，如果设置每个文章头部date结尾添加 +0800，本地运行慢八个小时，GitHub上正常
# 如果不设置，那么每个文章头部不需添加 +0800，本地运行快八个小时，GitHub上正常
timezone: Asia/Shanghai

## Gem
gems: [jekyll-paginate]
# highlighter: pygments


# 就是没有文章的时候显示的提示，未加无分类前:no-category-index,未加无标签前:no-tag-index,未加无归档前:no-archive
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'createNew_MDFile', 'no-archive', '/tag/no-tag-index', '/categories/no-category-index','old-reference']

github_username: jv0id

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

baidu_analysis: 05d061c4501320058e73b02c1bd8b1b8

# gitment
#comment_gitment_repo: http://8void.cn/
#comment_gitment_clientId: 0f1d860f67e66224d798
#comment_gitment_clientSecret: cb2ad5808b1089c1d84244427fc5387bb4ed57ac
